### ISSUE TITLE
Error on log4js configuration using log4js 6.6.1 and node.js 16.17.0

### ISSUE THREAD

**Issue by othomann** [log4js-node/log4js-node#1323]
Hi,

I am using log4js 6.6.1 with node.js 16.17.0.
On app startup, I am getting this error:
```
node:fs:1349
  handleErrorFromBinding(ctx);
  ^

Error: EACCES: permission denied, mkdir '/var/log/at-no-rotate/toolchain'
    at Object.mkdirSync (node:fs:1349:3)
    at mkdir (/home/node/node_modules/streamroller/lib/RollingFileWriteStream.js:270:19)
    at RollingFileStream._renewWriteStream (/home/node/node_modules/streamroller/lib/RollingFileWriteStream.js:299:5)
    at new RollingFileWriteStream (/home/node/node_modules/streamroller/lib/RollingFileWriteStream.js:94:10)
    at new RollingFileStream (/home/node/node_modules/streamroller/lib/RollingFileStream.js:18:5)
    at openTheStream (/home/node/node_modules/log4js/lib/appenders/file.js:64:20)
    at fileAppender (/home/node/node_modules/log4js/lib/appenders/file.js:84:16)
    at Object.configure (/home/node/node_modules/log4js/lib/appenders/file.js:144:10)
    at appender (/home/node/node_modules/log4js/lib/appenders/multiFile.js:44:29)
    at /home/node/node_modules/log4js/lib/log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (/home/node/node_modules/log4js/lib/log4js.js:42:21)
    at /home/node/node_modules/log4js/lib/clustering.js:25:28
    at Array.forEach (<anonymous>)
    at sendToListeners (/home/node/node_modules/log4js/lib/clustering.js:25:13)
    at Object.send (/home/node/node_modules/log4js/lib/clustering.js:91:7) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/var/log/at-no-rotate/toolchain'
```
The log4js config file looks like this:

```
---
appenders:
  console:
    type: console
    layout:
      type: pattern
      pattern: "[%d] [%p] [%c] %m"
      tokens: {}
  filtered-console:
    type: data-protection-filter
    appender: console

categories:
  default:
    appenders: [filtered-console]
    level: info
  request:
    appenders: [filtered-console]
    level: off
  service-instance:
    appenders: [filtered-console]
    level: info
  status:
    appenders: [filtered-console]
    level: info
  saucelabs:
    appenders: [filtered-console]
    level: error
  secrets-client:
    appenders: [filtered-console]
    level: info
  otc-utils/vault-client:
    appenders: [filtered-console]
    level: info
  version:
    appenders: [filtered-console]
    level: error
  byok-client:
    appenders: [filtered-console]
    level: all
  encrypt:
    appenders: [filtered-console]
    level: all
  service-instances:
    appenders: [filtered-console]
    level: all
  server:
    appenders: [filtered-console]
    level: all 
```

data-protection-filter is a log appender.
It worked fine with node.js 14.x, but I don't understand what could be the problem with node.js 16. If you have any idea what could be wrong, please let me know.

log4js is configure using this code:
```
// Configuration for logging
log4js.configure(yaml.safeLoad(fs.readFileSync("./config/log4js.yml")), {
	reloadSecs: 30
});
```

I can provide more details if needed.
